config/routes.rb
Rails.application.routes.draw do
  resources :projects

  get 'welcome/home'

  get 'welcome/projects'

  get 'welcome/about'

  root :to => 'welcome#home'
  
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :status, :number, :manager, :start, :end)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def projects
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StatusR</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div class="container">
    <div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<nav class="navbar navbar-default" role="navigation">
				<div class="navbar-header">    
 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="/welcome/home">Home</a>
		</div>
				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">

						<li>
							<%=link_to "About Us", welcome_about_path %>
						</li>
						<li>
							<%=link_to "Projects", projects_path %>
						</li>

					</ul>
					
					<ul class="nav navbar-nav navbar-right">

						<li class="dropdown">
							 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
							<ul class="dropdown-menu">
								<li>
									<a href="#">Action</a>
								</li>
								<li>
									<a href="#">Another action</a>
								</li>
								<li>
									<a href="#">Something else here</a>
								</li>
								<li class="divider">
								</li>
								<li>
									<a href="#">Separated link</a>
								</li>
							</ul>
						</li>
					</ul>
				</div>
				
			</nav>

		</div>
	</div>
</div>
    
  
<!--Navigation bar-->
    
 
<!--Navigation bar-->
  
    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash[:error]%>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
    <% elsif flash[:alert]%>
    <div class="alert">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
    <% end %>
  
<%= yield %>
 
</body>
  
   <p> <sup>Status Report webApp desgined for HP GFIT by Andres M</sup></p> 
</html>
</div>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :manager %><br>
    <%= f.text_field :manager %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.date_field :start %>
  </div>
  <div class="field">
    <%= f.label :end %><br>
    <%= f.date_field :end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>List of Projects</h1>
<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<table class="table table-condensed table-bordered">
				<thead>
					<tr>
						<th>
							Name
						</th>
						<th>
							Status
						</th>
						<th>
							Number
						</th>
						<th>
							Manager
						</th>
            <th>
							Start date
						</th>
            <th>
							End date
						</th>
					</tr>
				</thead>
				<tbody>
          <% @projects.each do |project| %>
					<tr>
						
						<td>
               <%= project.name %>
            </td>
						<td>
               <%= project.status %>
            </td>
						<td>
              <%= project.number %>
            </td>
			      <td>
              <%= project.manager %>
            </td>
				    <td>
              <%= project.start %>
            </td>
						<td>
              <%= project.end %>
            </td>					
            <td>
              <%= link_to 'Show', project %>
            </td>
            <td>
              <%= link_to 'Edit', edit_project_path(project) %>
            </td>
            <td>
              <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
			  
				<!-- <tr class="active"> ...puede ser danger o success o warning-- va alf inal de la linea-->
			
					</tr>
          <% end %>
        </tbody>
        
					
		</div>
	</div>
</div>


<table>
  <div class="well">
  <a class="btn btn-primary btn-large" href="projects/new">  Add Project </a>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/welcome/about.html.erb
<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<h3>
				About
			</h3>
			<p>
				This webapp is intended to be used as a tool to manage and identify the current status or projects. It helps to visualize the operation of proyects, the posible issues or risks that may impact to those projects as well as its resources and other relevant information.<br /><br />This tool also allows users (Portfolio managers and managers) to submit comments on each of the projects assigned to them. Therefore, this allows an 'in-report' communication between them, which may help reduce the response time for any issue presented.<br /><br />
			</p>
		</div>
	</div>
</div>

app/views/welcome/home.html.erb
			<div class="jumbotron">
				<h1>
					Status Report Tool
				</h1>
				<p>
				Hello, in this webapp you'll be able to mantain tracking of GFIT projects, please proceed to our 'Projects' section in order to start
				</p>
				<p>
					<a class="btn btn-primary btn-large" href="/projects">  Go to projects </a>
				</p>
			</div>

app/views/welcome/projects.html.erb
<h1>Welcome#projects</h1>
<p>Find me in app/views/welcome/projects.html.erb</p>